using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;

namespace EventFinalProject.Models {
    public class SampleData : DropCreateDatabaseIfModelChanges<EventFinalProjectDB> {
        protected override void Seed(EventFinalProjectDB context) {
            var categories = new List<Category> {
                new Category { Name = "Fitness & Health"},
                new Category { Name = "Food & Drink"},
                new Category { Name = "Animals"},
                new Category { Name = "Arts"},
                new Category { Name = "Education & Development"},
                new Category { Name = "Sports"},
                new Category { Name = "Family"},
                new Category { Name = "Music"},
                new Category { Name = "Technology"},
                new Category { Name = "Charity"},
                new Category { Name = "Comedy"},
                new Category { Name = "Nature & Outdoor"},
            };

            var organizers = new List<Organizer> {
                new Organizer{ FirstName = "Calli", LastName = "Karthan", PhoneNumber = "440-532-4444"},
                new Organizer{ FirstName = "Stuart", LastName = "Kolk", PhoneNumber = "330-219-0015"},
                new Organizer{ FirstName = "Summer", LastName = "Friedt", PhoneNumber = "216-210-3182"},
                new Organizer{ FirstName = "James", LastName = "Reed", PhoneNumber = "330-433-3056"},
                new Organizer{ FirstName = "Hannah", LastName = "Kichka", PhoneNumber = "440-525-6515"},
                new Organizer{ FirstName = "David", LastName = "Eckberg", PhoneNumber = "216-532-2705"},
                new Organizer{ FirstName = "Dan", LastName = "Kendrick", PhoneNumber = "330-610-4494"},
                new Organizer{ FirstName = "Nikki", LastName = "Moore", PhoneNumber = "440-590-0047"},
                new Organizer{ FirstName = "Alexias", LastName = "Baum", PhoneNumber = "216-219-0877"},
                new Organizer{ FirstName = "Minh", LastName = "Tan", PhoneNumber = "330-211-7339"},
                new Organizer{ FirstName = "Warren", LastName = "Puggins", PhoneNumber = "440-532-0210"},
            };

            new List<Event> {
                new Event {
                    Category = categories.Single(c => c.Name == "Comedy"),
                    Title = "Jon Lovitz Comedy Tour",
                    Description = "Join us to see one of the original masters of comedy Jon Lovitz! He started his career appearing as a regular on SNL, he has been in several blockbuster movies including: City Slickers, A League of Their Own and The Benchwarmers. Join us for a night filled with entertainment and gut splitting laughter! Additional appearances by: Chris Catan, Tim Meadows and Darryl Hammond.",
                    AddressLine1 = "1230 Northfiled Park Lane",
                    AddressLine2 = "Grand Ballroom",
                    City = "Northfield",
                    State = "Ohio",
                    Zipcode = 44270,
                    StartDateTime = DateTime.Now,
                   EndDateTime =  DateTime.Now,
                    Organizer = organizers.Single(o => o.LastName == "Karthan"),
                    MaxTickets = 500,
                    AvailableTickets = 500,
                    Price = 40.0M
                },
                new Event { Category = categories.Single(c => c.Name == "Fitness & Health"), Title = "Hot Yoga for Beginners", Description = "Join us to experience the latest fitness trend: Hot Yoga! You will be very hot, but very relaxed. Work up a sweat while holding still. This is a 6 week class held every Monday, Wednesday and Friday. Attend as many or as few classes as youd like for the cost.", AddressLine1 = "5600 West 130th Street", AddressLine2 = "Studio 3", City = "Parma", State = "Ohio", Zipcode = 44130, StartDateTime = new DateTime(2019,06,01,11,00,00), EndDateTime = new DateTime(2019,07,15,12,00,00), Organizer = organizers.SingleOrDefault(o => o.LastName == "Friedt"), MaxTickets = 30, AvailableTickets = 30, Price = 150.00M},
                new Event { Category = categories.Single(c => c.Name == "Comedy"), Title = "Jim Gaffigan Pale and Paler", Description = "Join us to see one of the original masters of comedy Jim Gaffigan! He started his career appearing regularly in the New York comedy scene, he has been in several hit comedy tours including: Beyond the Pale, HotPockets and Laugh Factory. Join us for a night filled with entertainment and gut splitting laughter!", AddressLine1 = "130 Center Street", AddressLine2 = "null", City = "Cleveland", State = "Ohio", Zipcode = 44113, StartDateTime = new DateTime(2019,05,18,08,00,00), EndDateTime = new DateTime(2019,05,18,12,00,00), Organizer = organizers.Single(o => o.LastName == "Eckberg"), MaxTickets = 800, AvailableTickets = 800, Price = 60.00M},
                new Event { Category = categories.Single(c => c.Name == "Fitness & Health"), Title = "2019 Cleveland Fun Run", Description = "Love running? Join us for this fun filled 5K, the 10th Annual Cleveland Fun Run! Run solo or bring a group of friends. Prizes will be given for the 1st, 2nd and 3rd place finishers for the following age groups: 25 and under, 26-35, 36-45, 46-55, 55 and over. Come on dow, lets get fit and have some fun!", AddressLine1 = "East 5th Street", AddressLine2 = "In front of the Fun Run Sign", City = "Cleveland", State = "Ohio", Zipcode = 44111, StartDateTime = new DateTime(2019,07,15,10,00,00), EndDateTime = new DateTime(2019,07,15,12,00,00), Organizer = organizers.Single(o => o.LastName == "Kolk"), MaxTickets = 300, AvailableTickets = 300, Price = 25.00M},
                new Event { Category = categories.Single(c => c.Name == "Food & Drink"), Title = "A Taste of Italy", Description = "Do you love Italian food? We're not talking Pizza and Spaghetti here, learn how to prepare authentic Italian cuisine in this weekly class. Bring friend or make some new ones at A taste of Italy! Join us for a night filled with entertainment and gut splitting laughter! Food and supplies provided, just bring your appetite and your thirst for culinary excellence.", AddressLine1 = "1230 Northfiled Park Lane", AddressLine2 = "Grand Ballroom", City = "Northfield", State = "Ohio", Zipcode = 44270, StartDateTime = new DateTime(2019,12,04,06,00,00), EndDateTime = new DateTime(2019,12,04,07,00,00), Organizer = organizers.Single(o => o.LastName == "Reed"), MaxTickets = 20, AvailableTickets = 20, Price = 50.00M},
                new Event { Category = categories.Single(c => c.Name == "Education & Development"), Title = "Fun with C# for Beginners", Description = "Join us to see one of the original masters of comedy Jon Lovitz! He started his career appearing as a regular on SNL, he has been in several blockbuster movies including: City Slickers, A League of Their Own and The Benchwarmers. Join us for a night filled with entertainment and gut splitting laughter! Additional appearances by: Chris Catan, Tim Meadows and Darryl Hammond.", AddressLine1 = "1230 Northfiled Park Lane", AddressLine2 = "Grand Ballroom", City = "Northfield", State = "Ohio", Zipcode = 44270, StartDateTime = new DateTime(2019,08,20,08,00,00), EndDateTime = new DateTime(2019,08,20,12,00,00), Organizer = organizers.Single(o => o.LastName == "Karthan"), MaxTickets = 500, AvailableTickets = 500, Price = 40.00M},
                new Event { Category = categories.Single(c => c.Name == "Fitness & Health"), Title = "Fit Fest 2019", Description = "Join us to see one of the original masters of comedy Jon Lovitz! He started his career appearing as a regular on SNL, he has been in several blockbuster movies including: City Slickers, A League of Their Own and The Benchwarmers. Join us for a night filled with entertainment and gut splitting laughter! Additional appearances by: Chris Catan, Tim Meadows and Darryl Hammond.", AddressLine1 = "1230 Northfiled Park Lane", AddressLine2 = "Grand Ballroom", City = "Northfield", State = "Ohio", Zipcode = 44270, StartDateTime = new DateTime(2019,05,06,08,00,00), EndDateTime = new DateTime(2019,05,06,10,00,00), Organizer = organizers.Single(o => o.LastName == "Karthan"), MaxTickets = 500, AvailableTickets = 500, Price = 40.00M},
                new Event { Category = categories.Single(c => c.Name == "Comedy"), Title = "Jon Lovitz Comedy Tour", Description = "Join us to see one of the original masters of comedy Jon Lovitz! He started his career appearing as a regular on SNL, he has been in several blockbuster movies including: City Slickers, A League of Their Own and The Benchwarmers. Join us for a night filled with entertainment and gut splitting laughter! Additional appearances by: Chris Catan, Tim Meadows and Darryl Hammond.", AddressLine1 = "1230 Northfiled Park Lane", AddressLine2 = "Grand Ballroom", City = "Northfield", State = "Ohio", Zipcode = 44270, StartDateTime = new DateTime(2019,08,20,08,00,00), EndDateTime = new DateTime(2019,08,20,12,00,00), Organizer = organizers.Single(o => o.LastName == "Karthan"), MaxTickets = 500, AvailableTickets = 500, Price = 40.00M},
                new Event { Category = categories.Single(c => c.Name == "Animals"), Title = "Spa Day for Pups", Description = "Join us to see one of the original masters of comedy Jon Lovitz! He started his career appearing as a regular on SNL, he has been in several blockbuster movies including: City Slickers, A League of Their Own and The Benchwarmers. Join us for a night filled with entertainment and gut splitting laughter! Additional appearances by: Chris Catan, Tim Meadows and Darryl Hammond.", AddressLine1 = "1230 Northfiled Park Lane", AddressLine2 = "Grand Ballroom", City = "Northfield", State = "Ohio", Zipcode = 44270, StartDateTime = new DateTime(2019,08,20,08,00,00), EndDateTime = new DateTime(2019,08,20,12,00,00), Organizer = organizers.Single(o => o.LastName == "Karthan"), MaxTickets = 500, AvailableTickets = 500, Price = 40.00M},
                new Event { Category = categories.Single(c => c.Name == "Arts"), Title = "Jon Lovitz Comedy Tour", Description = "Join us to see one of the original masters of comedy Jon Lovitz! He started his career appearing as a regular on SNL, he has been in several blockbuster movies including: City Slickers, A League of Their Own and The Benchwarmers. Join us for a night filled with entertainment and gut splitting laughter! Additional appearances by: Chris Catan, Tim Meadows and Darryl Hammond.", AddressLine1 = "1230 Northfiled Park Lane", AddressLine2 = "Grand Ballroom", City = "Northfield", State = "Ohio", Zipcode = 44270, StartDateTime = new DateTime(2019,08,20,08,00,00), EndDateTime = new DateTime(2019,08,20,12,00,00), Organizer = organizers.Single(o => o.LastName == "Karthan"), MaxTickets = 500, AvailableTickets = 500, Price = 40.00M},
                new Event { Category = categories.Single(c => c.Name == "Education & Development"), Title = "Jon Lovitz Comedy Tour", Description = "Join us to see one of the original masters of comedy Jon Lovitz! He started his career appearing as a regular on SNL, he has been in several blockbuster movies including: City Slickers, A League of Their Own and The Benchwarmers. Join us for a night filled with entertainment and gut splitting laughter! Additional appearances by: Chris Catan, Tim Meadows and Darryl Hammond.", AddressLine1 = "1230 Northfiled Park Lane", AddressLine2 = "Grand Ballroom", City = "Northfield", State = "Ohio", Zipcode = 44270, StartDateTime = new DateTime(2019,08,20,08,00,00), EndDateTime = new DateTime(2019,08,20,12,00,00), Organizer = organizers.Single(o => o.LastName == "Karthan"), MaxTickets = 500, AvailableTickets = 500, Price = 40.00M},
                new Event { Category = categories.Single(c => c.Name == "Comedy"), Title = "Jon Lovitz Comedy Tour", Description = "Join us to see one of the original masters of comedy Jon Lovitz! He started his career appearing as a regular on SNL, he has been in several blockbuster movies including: City Slickers, A League of Their Own and The Benchwarmers. Join us for a night filled with entertainment and gut splitting laughter! Additional appearances by: Chris Catan, Tim Meadows and Darryl Hammond.", AddressLine1 = "1230 Northfiled Park Lane", AddressLine2 = "Grand Ballroom", City = "Northfield", State = "Ohio", Zipcode = 44270, StartDateTime = new DateTime(2019,08,20,08,00,00), EndDateTime = new DateTime(2019,08,20,12,00,00), Organizer = organizers.Single(o => o.LastName == "Karthan"), MaxTickets = 500, AvailableTickets = 500, Price = 40.00M},
                new Event { Category = categories.Single(c => c.Name == "Food & Drink"), Title = "Jon Lovitz Comedy Tour", Description = "Join us to see one of the original masters of comedy Jon Lovitz! He started his career appearing as a regular on SNL, he has been in several blockbuster movies including: City Slickers, A League of Their Own and The Benchwarmers. Join us for a night filled with entertainment and gut splitting laughter! Additional appearances by: Chris Catan, Tim Meadows and Darryl Hammond.", AddressLine1 = "1230 Northfiled Park Lane", AddressLine2 = "Grand Ballroom", City = "Northfield", State = "Ohio", Zipcode = 44270, StartDateTime = new DateTime(2019,08,20,08,00,00), EndDateTime = new DateTime(2019,08,20,12,00,00), Organizer = organizers.Single(o => o.LastName == "Karthan"), MaxTickets = 500, AvailableTickets = 500, Price = 40.00M},
                new Event { Category = categories.Single(c => c.Name == "Animals"), Title = "Bird Watching 101", Description = "Join us to see one of the original masters of comedy Jon Lovitz! He started his career appearing as a regular on SNL, he has been in several blockbuster movies including: City Slickers, A League of Their Own and The Benchwarmers. Join us for a night filled with entertainment and gut splitting laughter! Additional appearances by: Chris Catan, Tim Meadows and Darryl Hammond.", AddressLine1 = "1230 Northfiled Park Lane", AddressLine2 = "Grand Ballroom", City = "Northfield", State = "Ohio", Zipcode = 44270, StartDateTime = new DateTime(2019,08,20,08,00,00), EndDateTime = new DateTime(2019,08,20,12,00,00), Organizer = organizers.Single(o => o.LastName == "Karthan"), MaxTickets = 500, AvailableTickets = 500, Price = 40.00M},
                new Event { Category = categories.Single(c => c.Name == "Arts"), Title = "Jon Lovitz Comedy Tour", Description = "Join us to see one of the original masters of comedy Jon Lovitz! He started his career appearing as a regular on SNL, he has been in several blockbuster movies including: City Slickers, A League of Their Own and The Benchwarmers. Join us for a night filled with entertainment and gut splitting laughter! Additional appearances by: Chris Catan, Tim Meadows and Darryl Hammond.", AddressLine1 = "1230 Northfiled Park Lane", AddressLine2 = "Grand Ballroom", City = "Northfield", State = "Ohio", Zipcode = 44270, StartDateTime = new DateTime(2019,08,20,08,00,00), EndDateTime = new DateTime(2019,08,20,12,00,00), Organizer = organizers.Single(o => o.LastName == "Karthan"), MaxTickets = 500, AvailableTickets = 500, Price = 40.00M},
                new Event { Category = categories.Single(c => c.Name == "Food & Drink"), Title = "Jon Lovitz Comedy Tour", Description = "Join us to see one of the original masters of comedy Jon Lovitz! He started his career appearing as a regular on SNL, he has been in several blockbuster movies including: City Slickers, A League of Their Own and The Benchwarmers. Join us for a night filled with entertainment and gut splitting laughter! Additional appearances by: Chris Catan, Tim Meadows and Darryl Hammond.", AddressLine1 = "1230 Northfiled Park Lane", AddressLine2 = "Grand Ballroom", City = "Northfield", State = "Ohio", Zipcode = 44270, StartDateTime = new DateTime(2019,08,20,08,00,00), EndDateTime = new DateTime(2019,08,20,12,00,00), Organizer = organizers.Single(o => o.LastName == "Karthan"), MaxTickets = 500, AvailableTickets = 500, Price = 40.00M},
                new Event { Category = categories.Single(c => c.Name == "Arts"), Title = "Jon Lovitz Comedy Tour", Description = "Join us to see one of the original masters of comedy Jon Lovitz! He started his career appearing as a regular on SNL, he has been in several blockbuster movies including: City Slickers, A League of Their Own and The Benchwarmers. Join us for a night filled with entertainment and gut splitting laughter! Additional appearances by: Chris Catan, Tim Meadows and Darryl Hammond.", AddressLine1 = "1230 Northfiled Park Lane", AddressLine2 = "Grand Ballroom", City = "Northfield", State = "Ohio", Zipcode = 44270, StartDateTime = new DateTime(2019,08,20,08,00,00), EndDateTime = new DateTime(2019,08,20,12,00,00), Organizer = organizers.Single(o => o.LastName == "Karthan"), MaxTickets = 500, AvailableTickets = 500, Price = 40.00M},
                new Event { Category = categories.Single(c => c.Name == "Education & Development"), Title = "Jon Lovitz Comedy Tour", Description = "Join us to see one of the original masters of comedy Jon Lovitz! He started his career appearing as a regular on SNL, he has been in several blockbuster movies including: City Slickers, A League of Their Own and The Benchwarmers. Join us for a night filled with entertainment and gut splitting laughter! Additional appearances by: Chris Catan, Tim Meadows and Darryl Hammond.", AddressLine1 = "1230 Northfiled Park Lane", AddressLine2 = "Grand Ballroom", City = "Northfield", State = "Ohio", Zipcode = 44270, StartDateTime = new DateTime(2019,08,20,08,00,00), EndDateTime = new DateTime(2019,08,20,12,00,00), Organizer = organizers.Single(o => o.LastName == "Karthan"), MaxTickets = 500, AvailableTickets = 500, Price = 40.00M},
                new Event { Category = categories.Single(c => c.Name == "Music"), Title = "Jon Lovitz Comedy Tour", Description = "Join us to see one of the original masters of comedy Jon Lovitz! He started his career appearing as a regular on SNL, he has been in several blockbuster movies including: City Slickers, A League of Their Own and The Benchwarmers. Join us for a night filled with entertainment and gut splitting laughter! Additional appearances by: Chris Catan, Tim Meadows and Darryl Hammond.", AddressLine1 = "1230 Northfiled Park Lane", AddressLine2 = "Grand Ballroom", City = "Northfield", State = "Ohio", Zipcode = 44270, StartDateTime = new DateTime(2019,08,20,08,00,00), EndDateTime = new DateTime(2019,08,20,12,00,00), Organizer = organizers.Single(o => o.LastName == "Karthan"), MaxTickets = 500, AvailableTickets = 500, Price = 40.00M},
                new Event { Category = categories.Single(c => c.Name == "Food & Drink"), Title = "Jon Lovitz Comedy Tour", Description = "Join us to see one of the original masters of comedy Jon Lovitz! He started his career appearing as a regular on SNL, he has been in several blockbuster movies including: City Slickers, A League of Their Own and The Benchwarmers. Join us for a night filled with entertainment and gut splitting laughter! Additional appearances by: Chris Catan, Tim Meadows and Darryl Hammond.", AddressLine1 = "1230 Northfiled Park Lane", AddressLine2 = "Grand Ballroom", City = "Northfield", State = "Ohio", Zipcode = 44270, StartDateTime = new DateTime(2019,08,20,08,00,00), EndDateTime = new DateTime(2019,08,20,12,00,00), Organizer = organizers.Single(o => o.LastName == "Karthan"), MaxTickets = 500, AvailableTickets = 500, Price = 40.00M},
                new Event { Category = categories.Single(c => c.Name == "Education & Development"), Title = "Jon Lovitz Comedy Tour", Description = "Join us to see one of the original masters of comedy Jon Lovitz! He started his career appearing as a regular on SNL, he has been in several blockbuster movies including: City Slickers, A League of Their Own and The Benchwarmers. Join us for a night filled with entertainment and gut splitting laughter! Additional appearances by: Chris Catan, Tim Meadows and Darryl Hammond.", AddressLine1 = "1230 Northfiled Park Lane", AddressLine2 = "Grand Ballroom", City = "Northfield", State = "Ohio", Zipcode = 44270, StartDateTime = new DateTime(2019,08,20,08,00,00), EndDateTime = new DateTime(2019,08,20,12,00,00), Organizer = organizers.Single(o => o.LastName == "Karthan"), MaxTickets = 500, AvailableTickets = 500, Price = 40.00M},
                new Event { Category = categories.Single(c => c.Name == "Animals"), Title = "Berea ARF Howl-oween Party", Description = "Join us to see one of the original masters of comedy Jon Lovitz! He started his career appearing as a regular on SNL, he has been in several blockbuster movies including: City Slickers, A League of Their Own and The Benchwarmers. Join us for a night filled with entertainment and gut splitting laughter! Additional appearances by: Chris Catan, Tim Meadows and Darryl Hammond.", AddressLine1 = "1230 Northfiled Park Lane", AddressLine2 = "Grand Ballroom", City = "Northfield", State = "Ohio", Zipcode = 44270, StartDateTime = new DateTime(2019,08,20,08,00,00), EndDateTime = new DateTime(2019,08,20,12,00,00), Organizer = organizers.Single(o => o.LastName == "Karthan"), MaxTickets = 500, AvailableTickets = 500, Price = 40.00M},
                new Event { Category = categories.Single(c => c.Name == "Arts"), Title = "Jon Lovitz Comedy Tour", Description = "Join us to see one of the original masters of comedy Jon Lovitz! He started his career appearing as a regular on SNL, he has been in several blockbuster movies including: City Slickers, A League of Their Own and The Benchwarmers. Join us for a night filled with entertainment and gut splitting laughter! Additional appearances by: Chris Catan, Tim Meadows and Darryl Hammond.", AddressLine1 = "1230 Northfiled Park Lane", AddressLine2 = "Grand Ballroom", City = "Northfield", State = "Ohio", Zipcode = 44270, StartDateTime = new DateTime(2019,08,20,08,00,00), EndDateTime = new DateTime(2019,08,20,12,00,00), Organizer = organizers.Single(o => o.LastName == "Karthan"), MaxTickets = 500, AvailableTickets = 500, Price = 40.00M},
                new Event { Category = categories.Single(c => c.Name == "Arts"), Title = "Jon Lovitz Comedy Tour", Description = "Join us to see one of the original masters of comedy Jon Lovitz! He started his career appearing as a regular on SNL, he has been in several blockbuster movies including: City Slickers, A League of Their Own and The Benchwarmers. Join us for a night filled with entertainment and gut splitting laughter! Additional appearances by: Chris Catan, Tim Meadows and Darryl Hammond.", AddressLine1 = "1230 Northfiled Park Lane", AddressLine2 = "Grand Ballroom", City = "Northfield", State = "Ohio", Zipcode = 44270, StartDateTime = new DateTime(2019,08,20,08,00,00), EndDateTime = new DateTime(2019,08,20,12,00,00), Organizer = organizers.Single(o => o.LastName == "Karthan"), MaxTickets = 500, AvailableTickets = 500, Price = 40.00M},
                new Event { Category = categories.Single(c => c.Name == "Education & Development"), Title = "Jon Lovitz Comedy Tour", Description = "Join us to see one of the original masters of comedy Jon Lovitz! He started his career appearing as a regular on SNL, he has been in several blockbuster movies including: City Slickers, A League of Their Own and The Benchwarmers. Join us for a night filled with entertainment and gut splitting laughter! Additional appearances by: Chris Catan, Tim Meadows and Darryl Hammond.", AddressLine1 = "1230 Northfiled Park Lane", AddressLine2 = "Grand Ballroom", City = "Northfield", State = "Ohio", Zipcode = 44270, StartDateTime = new DateTime(2019,08,20,08,00,00), EndDateTime = new DateTime(2019,08,20,12,00,00), Organizer = organizers.Single(o => o.LastName == "Karthan"), MaxTickets = 500, AvailableTickets = 500, Price = 40.00M},
                new Event { Category = categories.Single(c => c.Name == "Animals"), Title = "Boo at the Zoo", Description = "Join us to see one of the original masters of comedy Jon Lovitz! He started his career appearing as a regular on SNL, he has been in several blockbuster movies including: City Slickers, A League of Their Own and The Benchwarmers. Join us for a night filled with entertainment and gut splitting laughter! Additional appearances by: Chris Catan, Tim Meadows and Darryl Hammond.", AddressLine1 = "1230 Northfiled Park Lane", AddressLine2 = "Grand Ballroom", City = "Northfield", State = "Ohio", Zipcode = 44270, StartDateTime = new DateTime(2019,08,20,08,00,00), EndDateTime = new DateTime(2019,08,20,12,00,00), Organizer = organizers.Single(o => o.LastName == "Karthan"), MaxTickets = 500, AvailableTickets = 500, Price = 40.00M},
                new Event { Category = categories.Single(c => c.Name == "Education & Development"), Title = "Jon Lovitz Comedy Tour", Description = "Join us to see one of the original masters of comedy Jon Lovitz! He started his career appearing as a regular on SNL, he has been in several blockbuster movies including: City Slickers, A League of Their Own and The Benchwarmers. Join us for a night filled with entertainment and gut splitting laughter! Additional appearances by: Chris Catan, Tim Meadows and Darryl Hammond.", AddressLine1 = "1230 Northfiled Park Lane", AddressLine2 = "Grand Ballroom", City = "Northfield", State = "Ohio", Zipcode = 44270, StartDateTime = new DateTime(2019,08,20,08,00,00), EndDateTime = new DateTime(2019,08,20,12,00,00), Organizer = organizers.Single(o => o.LastName == "Karthan"), MaxTickets = 500, AvailableTickets = 500, Price = 40.00M},
                new Event { Category = categories.Single(c => c.Name == "Family"), Title = "Jon Lovitz Comedy Tour", Description = "Join us to see one of the original masters of comedy Jon Lovitz! He started his career appearing as a regular on SNL, he has been in several blockbuster movies including: City Slickers, A League of Their Own and The Benchwarmers. Join us for a night filled with entertainment and gut splitting laughter! Additional appearances by: Chris Catan, Tim Meadows and Darryl Hammond.", AddressLine1 = "1230 Northfiled Park Lane", AddressLine2 = "Grand Ballroom", City = "Northfield", State = "Ohio", Zipcode = 44270, StartDateTime = new DateTime(2019,08,20,08,00,00), EndDateTime = new DateTime(2019,08,20,12,00,00), Organizer = organizers.Single(o => o.LastName == "Karthan"), MaxTickets = 500, AvailableTickets = 500, Price = 40.00M},
                new Event { Category = categories.Single(c => c.Name == "Nature & Outdoor"), Title = "Jon Lovitz Comedy Tour", Description = "Join us to see one of the original masters of comedy Jon Lovitz! He started his career appearing as a regular on SNL, he has been in several blockbuster movies including: City Slickers, A League of Their Own and The Benchwarmers. Join us for a night filled with entertainment and gut splitting laughter! Additional appearances by: Chris Catan, Tim Meadows and Darryl Hammond.", AddressLine1 = "1230 Northfiled Park Lane", AddressLine2 = "Grand Ballroom", City = "Northfield", State = "Ohio", Zipcode = 44270, StartDateTime = new DateTime(2019,08,20,08,00,00), EndDateTime = new DateTime(2019,08,20,12,00,00), Organizer = organizers.Single(o => o.LastName == "Karthan"), MaxTickets = 500, AvailableTickets = 500, Price = 40.00M},
                new Event { Category = categories.Single(c => c.Name == "Sports"), Title = "Jon Lovitz Comedy Tour", Description = "Join us to see one of the original masters of comedy Jon Lovitz! He started his career appearing as a regular on SNL, he has been in several blockbuster movies including: City Slickers, A League of Their Own and The Benchwarmers. Join us for a night filled with entertainment and gut splitting laughter! Additional appearances by: Chris Catan, Tim Meadows and Darryl Hammond.", AddressLine1 = "1230 Northfiled Park Lane", AddressLine2 = "Grand Ballroom", City = "Northfield", State = "Ohio", Zipcode = 44270, StartDateTime = new DateTime(2019,08,20,08,00,00), EndDateTime = new DateTime(2019,08,20,12,00,00), Organizer = organizers.Single(o => o.LastName == "Karthan"), MaxTickets = 500, AvailableTickets = 500, Price = 40.00M},
                new Event { Category = categories.Single(c => c.Name == "Animals"), Title = "The Cleveland Aquarium Anniversary Party", Description = "Join us to see one of the original masters of comedy Jon Lovitz! He started his career appearing as a regular on SNL, he has been in several blockbuster movies including: City Slickers, A League of Their Own and The Benchwarmers. Join us for a night filled with entertainment and gut splitting laughter! Additional appearances by: Chris Catan, Tim Meadows and Darryl Hammond.", AddressLine1 = "1230 Northfiled Park Lane", AddressLine2 = "Grand Ballroom", City = "Northfield", State = "Ohio", Zipcode = 44270, StartDateTime = new DateTime(2019,08,20,08,00,00), EndDateTime = new DateTime(2019,08,20,12,00,00), Organizer = organizers.Single(o => o.LastName == "Karthan"), MaxTickets = 500, AvailableTickets = 500, Price = 40.00M},
                new Event { Category = categories.Single(c => c.Name == "Sports"), Title = "Jon Lovitz Comedy Tour", Description = "Join us to see one of the original masters of comedy Jon Lovitz! He started his career appearing as a regular on SNL, he has been in several blockbuster movies including: City Slickers, A League of Their Own and The Benchwarmers. Join us for a night filled with entertainment and gut splitting laughter! Additional appearances by: Chris Catan, Tim Meadows and Darryl Hammond.", AddressLine1 = "1230 Northfiled Park Lane", AddressLine2 = "Grand Ballroom", City = "Northfield", State = "Ohio", Zipcode = 44270, StartDateTime = new DateTime(2019,08,20,08,00,00), EndDateTime = new DateTime(2019,08,20,12,00,00), Organizer = organizers.Single(o => o.LastName == "Karthan"), MaxTickets = 500, AvailableTickets = 500, Price = 40.00M},
                new Event { Category = categories.Single(c => c.Name == "Fitness & Health"), Title = "Jon Lovitz Comedy Tour", Description = "Join us to see one of the original masters of comedy Jon Lovitz! He started his career appearing as a regular on SNL, he has been in several blockbuster movies including: City Slickers, A League of Their Own and The Benchwarmers. Join us for a night filled with entertainment and gut splitting laughter! Additional appearances by: Chris Catan, Tim Meadows and Darryl Hammond.", AddressLine1 = "1230 Northfiled Park Lane", AddressLine2 = "Grand Ballroom", City = "Northfield", State = "Ohio", Zipcode = 44270, StartDateTime = new DateTime(2019,08,20,08,00,00), EndDateTime = new DateTime(2019,08,20,12,00,00), Organizer = organizers.Single(o => o.LastName == "Karthan"), MaxTickets = 500, AvailableTickets = 500, Price = 40.00M},
                new Event { Category = categories.Single(c => c.Name == "Arts"), Title = "Jon Lovitz Comedy Tour", Description = "Join us to see one of the original masters of comedy Jon Lovitz! He started his career appearing as a regular on SNL, he has been in several blockbuster movies including: City Slickers, A League of Their Own and The Benchwarmers. Join us for a night filled with entertainment and gut splitting laughter! Additional appearances by: Chris Catan, Tim Meadows and Darryl Hammond.", AddressLine1 = "1230 Northfiled Park Lane", AddressLine2 = "Grand Ballroom", City = "Northfield", State = "Ohio", Zipcode = 44270, StartDateTime = new DateTime(2019,08,20,08,00,00), EndDateTime = new DateTime(2019,08,20,12,00,00), Organizer = organizers.Single(o => o.LastName == "Karthan"), MaxTickets = 500, AvailableTickets = 500, Price = 40.00M},
                new Event { Category = categories.Single(c => c.Name == "Nature & Outdoor"), Title = "Jon Lovitz Comedy Tour", Description = "Join us to see one of the original masters of comedy Jon Lovitz! He started his career appearing as a regular on SNL, he has been in several blockbuster movies including: City Slickers, A League of Their Own and The Benchwarmers. Join us for a night filled with entertainment and gut splitting laughter! Additional appearances by: Chris Catan, Tim Meadows and Darryl Hammond.", AddressLine1 = "1230 Northfiled Park Lane", AddressLine2 = "Grand Ballroom", City = "Northfield", State = "Ohio", Zipcode = 44270, StartDateTime = new DateTime(2019,08,20,08,00,00), EndDateTime = new DateTime(2019,08,20,12,00,00), Organizer = organizers.Single(o => o.LastName == "Karthan"), MaxTickets = 500, AvailableTickets = 500, Price = 40.00M},
                new Event { Category = categories.Single(c => c.Name == "Food & Drink"), Title = "Jon Lovitz Comedy Tour", Description = "Join us to see one of the original masters of comedy Jon Lovitz! He started his career appearing as a regular on SNL, he has been in several blockbuster movies including: City Slickers, A League of Their Own and The Benchwarmers. Join us for a night filled with entertainment and gut splitting laughter! Additional appearances by: Chris Catan, Tim Meadows and Darryl Hammond.", AddressLine1 = "1230 Northfiled Park Lane", AddressLine2 = "Grand Ballroom", City = "Northfield", State = "Ohio", Zipcode = 44270, StartDateTime = new DateTime(2019,08,20,08,00,00), EndDateTime = new DateTime(2019,08,20,12,00,00), Organizer = organizers.Single(o => o.LastName == "Karthan"), MaxTickets = 500, AvailableTickets = 500, Price = 40.00M},
                new Event { Category = categories.Single(c => c.Name == "Family"), Title = "Jon Lovitz Comedy Tour", Description = "Join us to see one of the original masters of comedy Jon Lovitz! He started his career appearing as a regular on SNL, he has been in several blockbuster movies including: City Slickers, A League of Their Own and The Benchwarmers. Join us for a night filled with entertainment and gut splitting laughter! Additional appearances by: Chris Catan, Tim Meadows and Darryl Hammond.", AddressLine1 = "1230 Northfiled Park Lane", AddressLine2 = "Grand Ballroom", City = "Northfield", State = "Ohio", Zipcode = 44270, StartDateTime = new DateTime(2019,08,20,08,00,00), EndDateTime = new DateTime(2019,08,20,12,00,00), Organizer = organizers.Single(o => o.LastName == "Karthan"), MaxTickets = 500, AvailableTickets = 500, Price = 40.00M},
                new Event { Category = categories.Single(c => c.Name == "Music"), Title = "Jon Lovitz Comedy Tour", Description = "Join us to see one of the original masters of comedy Jon Lovitz! He started his career appearing as a regular on SNL, he has been in several blockbuster movies including: City Slickers, A League of Their Own and The Benchwarmers. Join us for a night filled with entertainment and gut splitting laughter! Additional appearances by: Chris Catan, Tim Meadows and Darryl Hammond.", AddressLine1 = "1230 Northfiled Park Lane", AddressLine2 = "Grand Ballroom", City = "Northfield", State = "Ohio", Zipcode = 44270, StartDateTime = new DateTime(2019,08,20,08,00,00), EndDateTime = new DateTime(2019,08,20,12,00,00), Organizer = organizers.Single(o => o.LastName == "Karthan"), MaxTickets = 500, AvailableTickets = 500, Price = 40.00M},
                new Event { Category = categories.Single(c => c.Name == "Technology"), Title = "Jon Lovitz Comedy Tour", Description = "Join us to see one of the original masters of comedy Jon Lovitz! He started his career appearing as a regular on SNL, he has been in several blockbuster movies including: City Slickers, A League of Their Own and The Benchwarmers. Join us for a night filled with entertainment and gut splitting laughter! Additional appearances by: Chris Catan, Tim Meadows and Darryl Hammond.", AddressLine1 = "1230 Northfiled Park Lane", AddressLine2 = "Grand Ballroom", City = "Northfield", State = "Ohio", Zipcode = 44270, StartDateTime = new DateTime(2019,08,20,08,00,00), EndDateTime = new DateTime(2019,08,20,12,00,00), Organizer = organizers.Single(o => o.LastName == "Karthan"), MaxTickets = 500, AvailableTickets = 500, Price = 40.00M},
                new Event { Category = categories.Single(c => c.Name == "Food & Drink"), Title = "Jon Lovitz Comedy Tour", Description = "Join us to see one of the original masters of comedy Jon Lovitz! He started his career appearing as a regular on SNL, he has been in several blockbuster movies including: City Slickers, A League of Their Own and The Benchwarmers. Join us for a night filled with entertainment and gut splitting laughter! Additional appearances by: Chris Catan, Tim Meadows and Darryl Hammond.", AddressLine1 = "1230 Northfiled Park Lane", AddressLine2 = "Grand Ballroom", City = "Northfield", State = "Ohio", Zipcode = 44270, StartDateTime = new DateTime(2019,08,20,08,00,00), EndDateTime = new DateTime(2019,08,20,12,00,00), Organizer = organizers.Single(o => o.LastName == "Karthan"), MaxTickets = 500, AvailableTickets = 500, Price = 40.00M},
                new Event { Category = categories.Single(c => c.Name == "Music"), Title = "Jon Lovitz Comedy Tour", Description = "Join us to see one of the original masters of comedy Jon Lovitz! He started his career appearing as a regular on SNL, he has been in several blockbuster movies including: City Slickers, A League of Their Own and The Benchwarmers. Join us for a night filled with entertainment and gut splitting laughter! Additional appearances by: Chris Catan, Tim Meadows and Darryl Hammond.", AddressLine1 = "1230 Northfiled Park Lane", AddressLine2 = "Grand Ballroom", City = "Northfield", State = "Ohio", Zipcode = 44270, StartDateTime = new DateTime(2019,08,20,08,00,00), EndDateTime = new DateTime(2019,08,20,12,00,00), Organizer = organizers.Single(o => o.LastName == "Karthan"), MaxTickets = 500, AvailableTickets = 500, Price = 40.00M},
                new Event { Category = categories.Single(c => c.Name == "Sports"), Title = "Jon Lovitz Comedy Tour", Description = "Join us to see one of the original masters of comedy Jon Lovitz! He started his career appearing as a regular on SNL, he has been in several blockbuster movies including: City Slickers, A League of Their Own and The Benchwarmers. Join us for a night filled with entertainment and gut splitting laughter! Additional appearances by: Chris Catan, Tim Meadows and Darryl Hammond.", AddressLine1 = "1230 Northfiled Park Lane", AddressLine2 = "Grand Ballroom", City = "Northfield", State = "Ohio", Zipcode = 44270, StartDateTime = new DateTime(2019,08,20,08,00,00), EndDateTime = new DateTime(2019,08,20,12,00,00), Organizer = organizers.Single(o => o.LastName == "Karthan"), MaxTickets = 500, AvailableTickets = 500, Price = 40.00M},
                new Event { Category = categories.Single(c => c.Name == "Family"), Title = "Jon Lovitz Comedy Tour", Description = "Join us to see one of the original masters of comedy Jon Lovitz! He started his career appearing as a regular on SNL, he has been in several blockbuster movies including: City Slickers, A League of Their Own and The Benchwarmers. Join us for a night filled with entertainment and gut splitting laughter! Additional appearances by: Chris Catan, Tim Meadows and Darryl Hammond.", AddressLine1 = "1230 Northfiled Park Lane", AddressLine2 = "Grand Ballroom", City = "Northfield", State = "Ohio", Zipcode = 44270, StartDateTime = new DateTime(2019,08,20,08,00,00), EndDateTime = new DateTime(2019,08,20,12,00,00), Organizer = organizers.Single(o => o.LastName == "Karthan"), MaxTickets = 500, AvailableTickets = 500, Price = 40.00M},
                new Event { Category = categories.Single(c => c.Name == "Technology"), Title = "Jon Lovitz Comedy Tour", Description = "Join us to see one of the original masters of comedy Jon Lovitz! He started his career appearing as a regular on SNL, he has been in several blockbuster movies including: City Slickers, A League of Their Own and The Benchwarmers. Join us for a night filled with entertainment and gut splitting laughter! Additional appearances by: Chris Catan, Tim Meadows and Darryl Hammond.", AddressLine1 = "1230 Northfiled Park Lane", AddressLine2 = "Grand Ballroom", City = "Northfield", State = "Ohio", Zipcode = 44270, StartDateTime = new DateTime(2019,08,20,08,00,00), EndDateTime = new DateTime(2019,08,20,12,00,00), Organizer = organizers.Single(o => o.LastName == "Karthan"), MaxTickets = 500, AvailableTickets = 500, Price = 40.00M},
                new Event { Category = categories.Single(c => c.Name == "Fitness & Health"), Title = "Jon Lovitz Comedy Tour", Description = "Join us to see one of the original masters of comedy Jon Lovitz! He started his career appearing as a regular on SNL, he has been in several blockbuster movies including: City Slickers, A League of Their Own and The Benchwarmers. Join us for a night filled with entertainment and gut splitting laughter! Additional appearances by: Chris Catan, Tim Meadows and Darryl Hammond.", AddressLine1 = "1230 Northfiled Park Lane", AddressLine2 = "Grand Ballroom", City = "Northfield", State = "Ohio", Zipcode = 44270, StartDateTime = new DateTime(2019,08,20,08,00,00), EndDateTime = new DateTime(2019,08,20,12,00,00), Organizer = organizers.Single(o => o.LastName == "Karthan"), MaxTickets = 500, AvailableTickets = 500, Price = 40.00M},
                new Event { Category = categories.Single(c => c.Name == "Family"), Title = "Jon Lovitz Comedy Tour", Description = "Join us to see one of the original masters of comedy Jon Lovitz! He started his career appearing as a regular on SNL, he has been in several blockbuster movies including: City Slickers, A League of Their Own and The Benchwarmers. Join us for a night filled with entertainment and gut splitting laughter! Additional appearances by: Chris Catan, Tim Meadows and Darryl Hammond.", AddressLine1 = "1230 Northfiled Park Lane", AddressLine2 = "Grand Ballroom", City = "Northfield", State = "Ohio", Zipcode = 44270, StartDateTime = new DateTime(2019,08,20,08,00,00), EndDateTime = new DateTime(2019,08,20,12,00,00), Organizer = organizers.Single(o => o.LastName == "Karthan"), MaxTickets = 500, AvailableTickets = 500, Price = 40.00M},
                new Event { Category = categories.Single(c => c.Name == "Music"), Title = "Jon Lovitz Comedy Tour", Description = "Join us to see one of the original masters of comedy Jon Lovitz! He started his career appearing as a regular on SNL, he has been in several blockbuster movies including: City Slickers, A League of Their Own and The Benchwarmers. Join us for a night filled with entertainment and gut splitting laughter! Additional appearances by: Chris Catan, Tim Meadows and Darryl Hammond.", AddressLine1 = "1230 Northfiled Park Lane", AddressLine2 = "Grand Ballroom", City = "Northfield", State = "Ohio", Zipcode = 44270, StartDateTime = new DateTime(2019,08,20,08,00,00), EndDateTime = new DateTime(2019,08,20,12,00,00), Organizer = organizers.Single(o => o.LastName == "Karthan"), MaxTickets = 500, AvailableTickets = 500, Price = 40.00M},
                new Event { Category = categories.Single(c => c.Name == "Technology"), Title = "Jon Lovitz Comedy Tour", Description = "Join us to see one of the original masters of comedy Jon Lovitz! He started his career appearing as a regular on SNL, he has been in several blockbuster movies including: City Slickers, A League of Their Own and The Benchwarmers. Join us for a night filled with entertainment and gut splitting laughter! Additional appearances by: Chris Catan, Tim Meadows and Darryl Hammond.", AddressLine1 = "1230 Northfiled Park Lane", AddressLine2 = "Grand Ballroom", City = "Northfield", State = "Ohio", Zipcode = 44270, StartDateTime = new DateTime(2019,08,20,08,00,00), EndDateTime = new DateTime(2019,08,20,12,00,00), Organizer = organizers.Single(o => o.LastName == "Karthan"), MaxTickets = 500, AvailableTickets = 500, Price = 40.00M},
                new Event { Category = categories.Single(c => c.Name == "Music"), Title = "Jon Lovitz Comedy Tour", Description = "Join us to see one of the original masters of comedy Jon Lovitz! He started his career appearing as a regular on SNL, he has been in several blockbuster movies including: City Slickers, A League of Their Own and The Benchwarmers. Join us for a night filled with entertainment and gut splitting laughter! Additional appearances by: Chris Catan, Tim Meadows and Darryl Hammond.", AddressLine1 = "1230 Northfiled Park Lane", AddressLine2 = "Grand Ballroom", City = "Northfield", State = "Ohio", Zipcode = 44270, StartDateTime = new DateTime(2019,08,20,08,00,00), EndDateTime = new DateTime(2019,08,20,12,00,00), Organizer = organizers.Single(o => o.LastName == "Karthan"), MaxTickets = 500, AvailableTickets = 500, Price = 40.00M},
                new Event { Category = categories.Single(c => c.Name == "Fitness & Health"), Title = "Jon Lovitz Comedy Tour", Description = "Join us to see one of the original masters of comedy Jon Lovitz! He started his career appearing as a regular on SNL, he has been in several blockbuster movies including: City Slickers, A League of Their Own and The Benchwarmers. Join us for a night filled with entertainment and gut splitting laughter! Additional appearances by: Chris Catan, Tim Meadows and Darryl Hammond.", AddressLine1 = "1230 Northfiled Park Lane", AddressLine2 = "Grand Ballroom", City = "Northfield", State = "Ohio", Zipcode = 44270, StartDateTime = new DateTime(2019,08,20,08,00,00), EndDateTime = new DateTime(2019,08,20,12,00,00), Organizer = organizers.Single(o => o.LastName == "Karthan"), MaxTickets = 500, AvailableTickets = 500, Price = 40.00M},
                new Event { Category = categories.Single(c => c.Name == "Family"), Title = "Jon Lovitz Comedy Tour", Description = "Join us to see one of the original masters of comedy Jon Lovitz! He started his career appearing as a regular on SNL, he has been in several blockbuster movies including: City Slickers, A League of Their Own and The Benchwarmers. Join us for a night filled with entertainment and gut splitting laughter! Additional appearances by: Chris Catan, Tim Meadows and Darryl Hammond.", AddressLine1 = "1230 Northfiled Park Lane", AddressLine2 = "Grand Ballroom", City = "Northfield", State = "Ohio", Zipcode = 44270, StartDateTime = new DateTime(2019,08,20,08,00,00), EndDateTime = new DateTime(2019,08,20,12,00,00), Organizer = organizers.Single(o => o.LastName == "Karthan"), MaxTickets = 500, AvailableTickets = 500, Price = 40.00M},
                new Event { Category = categories.Single(c => c.Name == "Sports"), Title = "Jon Lovitz Comedy Tour", Description = "Join us to see one of the original masters of comedy Jon Lovitz! He started his career appearing as a regular on SNL, he has been in several blockbuster movies including: City Slickers, A League of Their Own and The Benchwarmers. Join us for a night filled with entertainment and gut splitting laughter! Additional appearances by: Chris Catan, Tim Meadows and Darryl Hammond.", AddressLine1 = "1230 Northfiled Park Lane", AddressLine2 = "Grand Ballroom", City = "Northfield", State = "Ohio", Zipcode = 44270, StartDateTime = new DateTime(2019,08,20,08,00,00), EndDateTime = new DateTime(2019,08,20,12,00,00), Organizer = organizers.Single(o => o.LastName == "Karthan"), MaxTickets = 500, AvailableTickets = 500, Price = 40.00M},
                new Event { Category = categories.Single(c => c.Name == "Sports"), Title = "Jon Lovitz Comedy Tour", Description = "Join us to see one of the original masters of comedy Jon Lovitz! He started his career appearing as a regular on SNL, he has been in several blockbuster movies including: City Slickers, A League of Their Own and The Benchwarmers. Join us for a night filled with entertainment and gut splitting laughter! Additional appearances by: Chris Catan, Tim Meadows and Darryl Hammond.", AddressLine1 = "1230 Northfiled Park Lane", AddressLine2 = "Grand Ballroom", City = "Northfield", State = "Ohio", Zipcode = 44270, StartDateTime = new DateTime(2019,08,20,08,00,00), EndDateTime = new DateTime(2019,08,20,12,00,00), Organizer = organizers.Single(o => o.LastName == "Karthan"), MaxTickets = 500, AvailableTickets = 500, Price = 40.00M},
                new Event { Category = categories.Single(c => c.Name == "Family"), Title = "Jon Lovitz Comedy Tour", Description = "Join us to see one of the original masters of comedy Jon Lovitz! He started his career appearing as a regular on SNL, he has been in several blockbuster movies including: City Slickers, A League of Their Own and The Benchwarmers. Join us for a night filled with entertainment and gut splitting laughter! Additional appearances by: Chris Catan, Tim Meadows and Darryl Hammond.", AddressLine1 = "1230 Northfiled Park Lane", AddressLine2 = "Grand Ballroom", City = "Northfield", State = "Ohio", Zipcode = 44270, StartDateTime = new DateTime(2019,08,20,08,00,00), EndDateTime = new DateTime(2019,08,20,12,00,00), Organizer = organizers.Single(o => o.LastName == "Karthan"), MaxTickets = 500, AvailableTickets = 500, Price = 40.00M},
                new Event { Category = categories.Single(c => c.Name == "Technology"), Title = "Jon Lovitz Comedy Tour", Description = "Join us to see one of the original masters of comedy Jon Lovitz! He started his career appearing as a regular on SNL, he has been in several blockbuster movies including: City Slickers, A League of Their Own and The Benchwarmers. Join us for a night filled with entertainment and gut splitting laughter! Additional appearances by: Chris Catan, Tim Meadows and Darryl Hammond.", AddressLine1 = "1230 Northfiled Park Lane", AddressLine2 = "Grand Ballroom", City = "Northfield", State = "Ohio", Zipcode = 44270, StartDateTime = new DateTime(2019,08,20,08,00,00), EndDateTime = new DateTime(2019,08,20,12,00,00), Organizer = organizers.Single(o => o.LastName == "Karthan"), MaxTickets = 500, AvailableTickets = 500, Price = 40.00M},
                new Event { Category = categories.Single(c => c.Name == "Fitness & Health"), Title = "Jon Lovitz Comedy Tour", Description = "Join us to see one of the original masters of comedy Jon Lovitz! He started his career appearing as a regular on SNL, he has been in several blockbuster movies including: City Slickers, A League of Their Own and The Benchwarmers. Join us for a night filled with entertainment and gut splitting laughter! Additional appearances by: Chris Catan, Tim Meadows and Darryl Hammond.", AddressLine1 = "1230 Northfiled Park Lane", AddressLine2 = "Grand Ballroom", City = "Northfield", State = "Ohio", Zipcode = 44270, StartDateTime = new DateTime(2019,08,20,08,00,00), EndDateTime = new DateTime(2019,08,20,12,00,00), Organizer = organizers.Single(o => o.LastName == "Karthan"), MaxTickets = 500, AvailableTickets = 500, Price = 40.00M},
            }.ForEach(e => context.Events.Add(e));
        }
    }
}